### ISSUE TITLE
Realized saving doesn't remove objects from unrealized set

### ISSUE THREAD

**Issue by crbellis** [PortalToBlockchainOrganization/CryptoCount#18]
When a user saves a set to realize, the unrealized set returns the entire set.

Expected behavior:
User saves set, realized portion is returned in realized set, remaining unrealized set is returned in unrealized set
<img width="1604" alt="Screen Shot 2021-08-17 at 8 44 07 PM" src="https://user-images.githubusercontent.com/63214891/129833904-77004ba5-501b-4268-9201-69806e751e23.png">
<img width="1600" alt="Screen Shot 2021-08-17 at 8 44 17 PM" src="https://user-images.githubusercontent.com/63214891/129833903-72d5a5e1-05d4-453f-b0d3-04106a5a5a75.png">
<img width="1601" alt="Screen Shot 2021-08-17 at 8 44 27 PM" src="https://user-images.githubusercontent.com/63214891/129833899-9023d26b-5808-4c5e-92ff-469e87f1c7d5.png">

**Comment by HenrikMoe** [comment]
saving realizing gives weird behavior negative value accounting entry for me
